// src/preact/src/app.tsx
import { DapDSCheckboxReact, DapDSTextareaReact, DapDSComboboxReact, DapDSDatePickerReact, DapDSOptionItemReact, DapDSSelectReact, DapDSButtonReact, DapDSInputReact, DapDSStackReact} from 'dap-design-system/dist/react'
import { Controller, useForm } from 'react-hook-form';
import './app.css'
import dayjs from 'dayjs'
import { useState } from 'preact/hooks';

export type Product = {
  id: number;
  title: string;
  description: string;
  category: string;
  price: number;
}

export function App() {
  let timeOutId = 0
  const {
    control,
    handleSubmit,
    setValue,
    setError,
    formState: { errors },
  } = useForm()

  const [products, setProducts] = useState<Product[]>([])
  
  const getProducts = async(filter: string) => {
    const response = await fetch(`https://dummyjson.com/products/search?q=${filter}`)
    const json = await response.json()
    return json.products.filter((item: any) => item.title.toLowerCase().startsWith(filter.toLowerCase()))
  }

  const onSubmit = (data: any) => {
    console.log('data', data)
    if (window.showDapSnackbar) {
      window.showDapSnackbar('Gratulálunk! Minden mező helyes!', {
        duration: 4500,
        alertType: 'successful',
        actions: [
          { href: 'https://sg.hu', text: 'SG' },
          { href: 'https://index.hu', text: 'Index' },
        ],
      })
    }
  }

  return (
    <>
      <div className="App">
        <form onSubmit={handleSubmit(onSubmit)} noValidate>
          <DapDSStackReact>
            <Controller
              name="name"
              control={control}
              render={({ field: { value } }) => (
                <DapDSInputReact
                  id="name"
                  label="Teljes név"
                  name="name"
                  value={value}
                  feedback={errors?.name?.message?.toString()}
                  feedbackType="negative"
                  onDdsChange={e => {
                    setValue('name', e.detail.value, { shouldValidate: true })
                  }}></DapDSInputReact>
              )}
              rules={{
                validate: {
                  required: value => {
                    if (!value) return 'Add meg a teljes neved!'
                  },
                },
              }}
            />
            <Controller
              name="prefix"
              control={control}
              render={({ field: { value } }) => (
                <DapDSSelectReact
                  id="prefix"
                  label="Megnevezés"
                  name="prefix"
                  value={value}
                  feedback={errors?.prefix?.message?.toString()}
                  feedbackType="negative"
                  onDdsChange={e => {
                    setValue('prefix', e.detail.value)
                  }}>
                    <DapDSOptionItemReact value="mr">Úr</DapDSOptionItemReact>
                    <DapDSOptionItemReact value="mrs">Hölgy</DapDSOptionItemReact>
                    <DapDSOptionItemReact value="miss">Kisasszony</DapDSOptionItemReact>
                </DapDSSelectReact>
              )}
              rules={{
                validate: {
                  required: value => {
                    if (!value) return 'Válassz megnevezést!'
                  },
                },
              }}
            />
            <Controller
              name="email"
              control={control}
              render={({ field: { value } }) => (
                <DapDSInputReact
                  id="email"
                  label="E-mail cím"
                  name="email"
                  value={value}
                  type="email"
                  feedback={errors?.email?.message?.toString()}
                  feedbackType="negative"
                  onDdsChange={e => {
                    setValue('email', e.detail.value, { shouldValidate: true })
                  }}></DapDSInputReact>
              )}
              rules={{
                validate: {
                  required: value => {
                    if (!value) return 'Add meg az e-mail címed!'
                  },
                  pattern: value => {
                    if (!value.match(/[^@\s]+@[^@\s]+\.[^@\s]+/))
                      return 'Az e-mail cím formátuma helytelen!'
                  },
                },
              }}
            />
            <Controller
              name="datepicker"
              control={control}
              render={({ field: { value } }) => (
                <DapDSDatePickerReact
                  id="datepicker"
                  label="Születési dátum"
                  description="Add meg a születési dátumod!"
                  name="datepicker"
                  value={value}
                  feedback={errors?.datepicker?.message?.toString()}
                  feedbackType={errors?.datepicker ? 'negative' : 'positive'}
                  onDdsChange={(e) => {
                    console.log(e)
                    setValue('datepicker', e.detail.value, { shouldValidate: true })}
                  }
                  onDdsInvalidDate={(e) => {
                    console.log(e)
                    if (e.detail.type === 'invalid') {
                      setError('datepicker', { message: `Érvénytelen dátum: ${dayjs.Ls[dayjs.locale()].formats.L}` })
                    }

                    if (e.detail.type === 'out-of-range') {
                      setError('datepicker', { message: 'Nem választható dátum!' })
                    }
                  }}
                  onDdsValidDate={(e) => {
                    console.log(e)
                    setError('datepicker', { message: '' })
                  }}
                >
                </DapDSDatePickerReact>
              )}
              rules={{
                validate: {
                  required: value => {
                    if (!value) return 'Add meg a születési dátumod!'
                  },
                },
              }}
            />
            <Controller
              name="product"
              control={control}
              render={({ field: { value } }) => (
                <DapDSComboboxReact
                  id="product"
                  label="Kedvenc terméked"
                  name="product"
                  value={value}
                  feedback={errors?.product?.message?.toString()}
                  feedbackType="negative"
                  onDdsChange={e => {
                    setValue('product', e.detail?.value)
                  }}
                  onDdsInput={e => {
                    const productFilter = e?.detail?.input;
                    if (productFilter) {
                      clearTimeout(timeOutId);
                      timeOutId = setTimeout(() => {
                        getProducts(productFilter)
                          .then((products: Product[]) => {
                            if (products) {
                              setProducts([...products])
                            }
                          })
                      }, 300);
                    }
                  }}
                  sync
                  placeholder="Válassz egy terméket">
                  {products?.map((item: Product) => (
                    <DapDSOptionItemReact key={item.id} value={item.id} label={item.title}>
                      {item.title}
                    </DapDSOptionItemReact>
                  ))}
                </DapDSComboboxReact>
              )}
              rules={{
                validate: {
                  required: value => {
                    if (!value) return 'Válassz egy terméket!'
                  },
                },
              }}
            />
            <Controller
              name="subject"
              control={control}
              render={({ field: { value } }) => (
                <DapDSInputReact
                  id="subject"
                  label="Tárgy"
                  optional
                  optionalLabel="(Nem kötelező)"
                  name="subject"
                  value={value}
                  onDdsChange={e => {
                    setValue('subject', e.detail.value)
                  }}></DapDSInputReact>
              )}
            />
            <Controller
              name="message"
              control={control}
              render={({ field: { value } }) => (
                <DapDSTextareaReact
                  id="message"
                  label="Üzenet"
                  name="message"
                  value={value}
                  feedback={errors?.message?.message?.toString()}
                  feedbackType="negative"
                  onDdsChange={e => {
                    setValue('message', e.detail.value, { shouldValidate: true })
                  }}></DapDSTextareaReact>
              )}
              rules={{
                validate: {
                  required: value => {
                    if (!value) return 'Írd be az üzeneted!'
                  },
                },
              }}
            />
            <Controller
              name="consent"
              control={control}
              render={({ field: { value } }) => (
                <DapDSCheckboxReact
                  id="consent"
                  label="Megnyitottam, elolvastam és elfogadom az Adatkezelési tájékoztatót."
                  name="consent"
                  checked={value}
                  feedback={errors?.consent?.message?.toString()}
                  feedbackType="negative"
                  onDdsChange={e => {
                    setValue('consent', e.detail.checked, {
                      shouldValidate: true,
                    })
                  }}></DapDSCheckboxReact>
              )}
              rules={{
                validate: {
                  required: value => {
                    if (!value) return 'Fogadd el az Adatkezelési tájékoztatót!'
                  },
                },
              }}
            />
            <DapDSButtonReact htmlType="submit">Küldés</DapDSButtonReact>
          </DapDSStackReact>
        </form>
      </div>
    </>
  )
}

// src/solid/src/App.tsx
import { createStore } from 'solid-js/store';
import './App.css'
import DapDSButtonSolid from './components/button'
import DapDSInputSolid from './components/input'
import DapDSOptionItemSolid from './components/option';
import DapDSSelectSolid from './components/select';
import DapDSStackSolid from './components/stack'
import DapDSDatePickerSolid from './components/datepicker';
import DapDSTextareaSolid from './components/textarea';
import DapDSCheckboxSolid from './components/checkbox';
import DapDSComboboxSolid from './components/combobox';
import { createSignal, For } from 'solid-js';
import DapDSSnackbarSolid from './components/snackbar';

declare global {
  interface Window {
    showDapSnackbar?: (message: string, options?: any) => void
  }
}

interface FormFields {
  name: string;
  prefix: string;
  email: string;
  birthDate: string;
  product: string;
  subject: string;
  message: string;
  consent: boolean;
}

export type Product = {
  id: number;
  title: string;
  description: string;
  category: string;
  price: number;
}

function App() {
  let timeOutId = 0;
  const [products, setProducts] = createSignal<Product[]>([]);
  const [form, setForm] = createStore<FormFields>({
    name: "",
    prefix: "",
    email: "",
    birthDate: "",
    product: "",
    subject: "",
    message: "",
    consent: false,
  });

  const [errors, setErrors] = createStore({
    name: "",
    prefix: "",
    email: "",
    birthDate: "",
    product: "",
    subject: "",
    message: "",
    consent: "",
  });

  const getProducts = async(filter: string) => {
    const response = await fetch(`https://dummyjson.com/products/search?q=${filter}`);
    const json = await response.json();
    return json.products.filter((item: any) => item.title.toLowerCase().startsWith(filter.toLowerCase()));
  }

  const onSubmit = (e: Event) => {
    e.preventDefault();
    if (window.showDapSnackbar) {
      window.showDapSnackbar('Gratulálunk! Minden mező helyes!', {
        duration: 4500,
        alertType: 'successful',
        actions: [
          { href: 'https://sg.hu', text: 'SG' },
          { href: 'https://index.hu', text: 'Index' },
        ],
      })
    }
  }

  const getFormFieldValue = (field: keyof FormFields): string | boolean=> form[field];
  const updateErrorField = (field: keyof FormFields, value: string) => setErrors({ [field]: value });

  const validateRequired = (field: keyof FormFields, message: string): void => {
    if (!getFormFieldValue(field)) {
      updateErrorField(field, message)
    } else {
      updateErrorField(field, '')
    }
  }

  const validateEmailPattern = (field: keyof FormFields, message: string): void => {
    const fieldValue = getFormFieldValue(field);
    if (typeof fieldValue === 'string' && !fieldValue.match(/[^@\s]+@[^@\s]+\.[^@\s]+/)) {
      updateErrorField(field, message);
    } else {
      updateErrorField(field, '');
    }
  }

  return (
    <>
      <div>
        <DapDSSnackbarSolid></DapDSSnackbarSolid>
        <form>
          <DapDSStackSolid>
            <DapDSInputSolid
              id="name"
              label="Teljes név"
              name="name"
              feedbackType="negative"
              value={form.name}
              feedback={errors?.name?.toString()}
              onDdsChange={(nameValue: string) => {
                setForm({name: nameValue});
                validateRequired('name', 'Add meg a teljes neved!');
              }}
            >
            </DapDSInputSolid>
            <DapDSSelectSolid
              id="prefix"
              label="Megnevezés"
              name="prefix"
              value={form.prefix}
              onDdsChange={(selectValue: string) => setForm({prefix: selectValue})}
              >
                <DapDSOptionItemSolid value="mr">Úr</DapDSOptionItemSolid>
                <DapDSOptionItemSolid value="mrs">Hölgy</DapDSOptionItemSolid>
                <DapDSOptionItemSolid value="miss">Kisasszony</DapDSOptionItemSolid>
            </DapDSSelectSolid>
            <DapDSInputSolid
              id="email"
              label="E-mail cím"
              name="email"
              value={form.email}
              feedbackType="negative"
              feedback={errors?.email?.toString()}
              onDdsChange={(emailValue: string) => {
                setForm({email: emailValue});
                validateEmailPattern('email', 'Az e-mail cím formátuma helytelen vagy üres!');
              }}
            ></DapDSInputSolid>
            <DapDSDatePickerSolid
              id="birthDate"
              label="Születési dátum"
              name="datepicker"
              value={form.birthDate}
              feedbackType="negative"
              feedback={errors?.birthDate?.toString()}
              onDdsChange={(birthDateValue: string) => {
                setForm({birthDate: birthDateValue});
                validateRequired('birthDate', 'Add meg a születési dátumod!');
              }}
              >
            </DapDSDatePickerSolid>
            <DapDSComboboxSolid
              id="product"
              label="Kedvenc terméked"
              name="product"
              value={form.product}
              feedbackType="negative"
              onDdsChange={(productValue: string) => setForm({product: productValue})}
              onDdsInput={
                (productFilter: string) => {
                  if (productFilter) {
                    clearTimeout(timeOutId);
                    timeOutId = setTimeout(() => {
                      getProducts(productFilter)
                        .then((products: Product[]) => {
                          if (products) {
                            setProducts([...products])
                          }
                        })
                    }, 300);
                  }
              }}
              sync
              placeholder="Válassz egy terméket">
                <For each={products()}>
                  {(item, _index) => (
                    <DapDSOptionItemSolid key={item.id} value={item.id as unknown as string} label={item.title}>
                    {item.title}
                  </DapDSOptionItemSolid>
                  )}
                </For>
            </DapDSComboboxSolid>
            <DapDSInputSolid
              id="subject"
              label="Tárgy"
              name="subject"
              value={form.subject}
              feedbackType="negative"
              onDdsChange={(subjectValue: string) => setForm({subject: subjectValue})}
            ></DapDSInputSolid>
            <DapDSTextareaSolid
              id="message"
              label="Üzenet"
              name="message"
              value={form.message}
              feedbackType="negative"
              feedback={errors?.message?.toString()}
              onDdsChange={(messageValue: string) => {
                setForm({message: messageValue});
                validateRequired('message', 'Írd be az üzeneted!');
              }}
            ></DapDSTextareaSolid>
            <DapDSCheckboxSolid
              id="consent"
              label="Megnyitottam, elolvastam és elfogadom az Adatkezelési tájékoztatót."
              name="consent"
              feedbackType="negative"
              checked={form.consent}
              feedback={errors?.consent?.toString()}
              onDdsChange={(consentValue: boolean) => {
                setForm({consent: consentValue});
                validateRequired('consent', 'Fogadd el az Adatkezelési tájékoztatót!');
            }}
            ></DapDSCheckboxSolid>
            <DapDSButtonSolid onClick={(e: Event) => onSubmit(e)} htmlType="submit">Küldés</DapDSButtonSolid>
          </DapDSStackSolid>
          <div>
              <h3>Form Data:</h3>
              <pre>{JSON.stringify(form, null, 2)}</pre>
          </div>
        </form>
      </div>
    </>
  )
}

export default App
