// src/preact/src/main.tsx
import { render } from 'preact'
import './index.css'
import { App } from './app.tsx'
import 'dap-design-system/dist/light.theme.css'
import dayjs from 'dayjs'
import customParseFormat from 'dayjs/plugin/customParseFormat' // ES 2015
import localeData from 'dayjs/plugin/localeData'
import LocalizedFormat from 'dayjs/plugin/localizedFormat'
import { DapDSSnackbarReact } from 'dap-design-system/dist/react';

dayjs.extend(localeData)
dayjs.extend(LocalizedFormat)
dayjs.extend(customParseFormat)

const Root = () => (
    <div>
      <DapDSSnackbarReact></DapDSSnackbarReact>
      <App />
    </div>
  );
render(<Root />, document.getElementById('app')!);

// src/solid/src/index.tsx
/* @refresh reload */
import { render } from 'solid-js/web'
import './index.css'
import 'dap-design-system/dist/light.theme.css'
import './custom-elements.d.ts';
import 'dap-design-system/dist/dds.js';
import App from './App.tsx'

const root = document.getElementById('root')
render(() => <App />, root!)
